#!/bin/bash -eu
#
# entrypoint.sh
#
# Copyright (c) 2016 Junpei Kawamoto
#
# This software is released under the MIT License.
#
# http://opensource.org/licenses/mit-license.php
#
PATH="$GOPATH/bin:$PATH"

if [[ $# = 0 ]]; then
  exec bash
fi


echo "Before Script Steps:"
{{range .BeforeScript}}
echo "{{.}}"
{{.}}
{{end}}

echo "Script Steps:"
{{range .Script}}
echo "{{.}}"
{{.}}
{{end}}
