#!/bin/bash -eu
#
# entrypoint-go
#
# Copyright (c) 2016-2017 Junpei Kawamoto
#
# This software is released under the MIT License.
#
# http://opensource.org/licenses/mit-license.php
#
PATH="$GOPATH/bin:$PATH"

if [[ $# = 0 ]]; then
  exec bash
fi

if [[ $1 = "any" ]]; then
  TRAVIS_GO_VERSION=$(go version | cut -f 3 -d " " | sed s/go//g)
else
  TRAVIS_GO_VERSION=$1
  echo "Set Go version: $TRAVIS_GO_VERSION"
  eval "$(GIMME_GO_VERSION=$TRAVIS_GO_VERSION gimme)"
fi

for e in ${@:2:($#-1)}; do
  echo "Set environment: $e"
  env $e
done

echo "Install Steps:"
{{if .Install}}
{{range .Install}}
echo "{{.}}"
{{.}}
{{end}}
{{else}}
echo "go get -t ./..."
go get -t ./...
{{end}}

echo "Before Script Steps:"
{{range .BeforeScript}}
echo "{{.}}"
{{.}}
{{end}}

echo "Script Steps:"
{{/* if script isn't givenm use make or the default golang test command. */}}
{{if .Script}}
{{range .Script}}
echo "{{.}}"
{{.}}
{{end}}
{{else}}
if [ -e GNUMakefile ] || [ -e Makefile ] || [ -e BSDmakefile ] || [ -e makefile ]; then
  make
else
  {{if .GoBuildArgs}}
  go test {{.GoBuildArgs}}
  {{else}}
  go test -v ./...
  {{end}}
fi
{{end}}
