#!/bin/bash -eu
#
# entrypoint-python
#
# Copyright (c) 2016 Junpei Kawamoto
#
# This software is released under the MIT License.
#
# http://opensource.org/licenses/mit-license.php
#
PATH="/root/.pyenv/bin:$PATH"
eval "$(pyenv init -)" && \
eval "$(pyenv virtualenv-init -)"

if [[ $# = 0 ]]; then
  exec bash
fi

readonly PYVERSION=$(pyenv install -l | sed "s/ //g" | grep -E "^$1($|[^-])" | tail -1)
echo "Set Python version: $PYVERSION"
pyenv install $PYVERSION
pyenv local $PYVERSION

for e in ${@:2:($#-1)}; do
  echo "Set environment: $e"
  declare -x $e
done

echo "Install Steps:"
if [[ -e requirements.txt ]]; then
  pip install -r requirements.txt
fi
{{range .Install}}
echo "{{.}}"
{{.}}
{{end}}

echo "Before Script Steps:"
{{range .BeforeScript}}
echo "{{.}}"
{{.}}
{{end}}

echo "Script Steps:"
{{range .Script}}
echo "{{.}}"
{{.}}
{{end}}
