baseurl = "https://jkawamoto.github.io/loci/"
languageCode = "en-us"
title = "Loci"
theme = "github-project-landing-page"

[params]
    SubTitle = "Testing remote CI scripts locally"
    Description = """\
      Loci runs CI tests locally to make sure your commits will pass such tests\
      before pushing to a remote repository.\
      """
    AuthorName = "Junpei Kawamoto"
    AuthorURL = "https://www.jkawamoto.info/"
    GithubURL = "https://github.com/jkawamoto/loci"
    ProfilePicture = "img/dna.png"

    GithubRepo = "loci"
    GithubOrg = "jkawamoto"

    GoogleAnalytics = "UA-82315630-1"
    GoogleAdSenseClient = "ca-pub-4734862314145555"
    GoogleAdSenseSlot = "4875187824"

    HighlightStyle = "//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/agate.min.css"
    HighlightLanguages = []
    AddThis = "ra-57f529147128b1fb"

    Favicon = "img/favicon.ico"
    Icon16 = "img/icon_16.png"
    Icon32 = "img/icon_32.png"
    Icon96 = "img/icon_96.png"

    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"
